export const INIT_CALL = 'INIT_CALL'

export const GET_OCCURRENCES = 'GET_OCCURRENCES'
export const SET_OCCURRENCES = 'SET_OCCURRENCES'
export const SET_OCCURRENCE_BY_ID = 'SET_OCCURRENCE_BY_ID'
export const POST_OCCURRENCE = 'POST_OCCURRENCE'

export const SET_RESOURCES = 'SET_RESOURCES'
export const GET_RESOURCES = 'GET_RESOURCES'

export const SEND_OCCURRENCE_TO_RESOURCE = 'SEND_OCCURRENCE_TO_RESOURCE'
